Makefile
requirements-dev.txt
requirements.txt
setup.py
src/turbine/function-deploy/Dockerfile
src/turbine/function-deploy/function-app/__init__.py
src/turbine/function-deploy/function-app/main.py
src/turbine/function-deploy/function-app/record.py
src/turbine/runtime/info.py
src/turbine/runtime/local.py
src/turbine/runtime/platform.py
src/turbine/runtime/types.py
src/turbine/templates/python/main.py
src/turbine/templates/python/requirements.txt

add set_secrets function to runtimes

---

src/turbine/runtime/platform.py

Sometimes, output is a list

---

src/turbine/templates/python/main.py

Logging from inside a Process

---

src/turbine/templates/python/README.md
src/turbine/templates/python/main.py

Keep the latest function code consistent everywhere
Fixes https://github.com/meroxa/meroxa-docs/issues/117

Updated function template and docs

---

src/turbine/function-deploy/Dockerfile

Make sure that container running the Function image is nonroot.
Fixes # https://github.com/meroxa/product/issues/415

Add nonroot user to dockerfile

---

docs/PUBLISHING.md
src/turbine/templates/python/main.py

Update the publishing instructions for turbine-py. Additionally, update the app init template 

Update publishing instruction; update template

---

src/turbine/runtime/platform.py

Auto-configures Kafka configs (sets `conduit` to `true` and maps `collection` to `topic`).
Fixes [# (issue)](https://github.com/meroxa/product/issues/560)

feat: auto-configure kafka resources for Records() and Write()

---

src/turbine/runner/runner.py

Fixes https://github.com/meroxa/product/issues/550
After:

Return JSON spec to the CLI

---

requirements.txt
src/turbine/runtime/platform.py

Adds support for Confluent Cloud resource.

Add support for confluent cloud resource

---

.github/workflows/ci.yml
src/turbine/function-deploy/Dockerfile
tox.ini

Ensure support for python versions 3.9 -> 3.11 
Run turbine-py tests on a variety of platforms and versions to ensure continued, multi-platform support. 
Fixes #129 

Ensure turbine-py works for multiple versions

---

.github/workflows/release.yml

Fixes formatting error in release yml

fix: update release yml

---

.github/workflows/release.yml

Attempt to fix the release yml formatting yet again

fix: fix yml formatting

---

.github/workflows/release.yml

fix: failing build

---

.github/workflows/release.yml
setup.cfg

fix: build command

---

docs/PUBLISHING.md

Add more documentation for semantic release, and create a new release

fix: add more documentation for semantic release

---

src/turbine/cli.py
src/turbine/function_deploy/function_app/requirements.txt
src/turbine/templates/python/requirements.txt

Version command has some left over cruft from the previous way of determining the version. 

fix: version command

---

requirements.txt
setup.cfg
src/turbine/templates/python/README.md

Bump meroxa-py to address an issue with parsing function responses 

fix: properly parse function deploy responses

---

.github/pull_request_template.md

Demo as part of PR template
Related to https://github.com/meroxa/product/issues/647

Update PR template around testing demo

---

.github/workflows/dependabot-auto-merge-py.yml

Automate closing more dependency PRs
Related to https://github.com/meroxa/engineering/issues/51
| before | after |
|--------|-------|
|||

Automerge Dependabot PRs with passing automation

---

pkg/turbine/src/turbine_app/client.py
src/turbine/runner/app_generate.py
src/turbine/runner/baserunner.py
src/turbine/runner/runner.py

More path instances where we are not correctly accounting for windows.
The generate app changes dont really matter since that code is not being used by the CLI

fix: more windows paths

---

pkg/turbine/__init__.py
pkg/turbine/src/function_deploy/requirements.txt

Builds and releases are failing. This should unblock builds. 

feat: release turbine core

---

pkg/turbine/src/function_deploy/requirements.txt
requirements.txt

BREAKING CHANGE: Turbine core is now defaulted for all turbine applications
| before | after |
|--------|-------|
|||

feat: turbine core 2.0.0

---

pkg/turbine/proto/turbine.proto
pkg/turbine/src/function_deploy/requirements.txt
pkg/turbine/src/turbine_app/proto_gen/turbine_pb2.py
pkg/turbine/src/turbine_app/proto_gen/turbine_pb2.pyi
requirements.txt
setup.cfg

Updating .proto and installing needed libraries 

fix: update proto buffs and install required libraries

---

tests/turbine/run.py

To have the option to run all our customer facing code on either Unix or Windows systems
Related to https://github.com/meroxa/product/issues/815
| before | after |
|--------|-------|
|||

Do not use backslashes in case the tests run on Windows

---

.github/workflows/release.yml

The previous turbine-py release action ran but did not upload any artifacts to pypi
| before | after |
|--------|-------|
|||

fix: Publish artifacts for newest version of turbine-py

---

pyproject.toml
setup.cfg

Updated semantic release version has an update configuration format as well.

fix: semantic release config update

---

pkg/turbine/src/turbine_app/app.py
pkg/turbine/src/turbine_app/client.py

Fix function always getting executed for turbine py
Fixes # https://github.com/meroxa/turbine-go/issues/162

Fix function always getting executed for turbine py
